### ISSUE TITLE
[Bug]: Juggling Commits #2

### ISSUE THREAD

**Issue by mg901** [pcottle/learnGitBranching#1016]
Hi, Peter! Thank you for your awesome game!)
If I use the command `git cherry-pick C2 C3` the level is passed, but my solution is wrong.

**Comment by pcottle** [comment]
the goal specifically allows a >= for the c2 to c3 jump:
https://github.com/pcottle/learnGitBranching/blob/main/src/levels/mixed/jugglingCommits2.js#L10-L17

which is why it works. there are edge cases in the levels where we might allow an invalid solution, but its to facilitate people solving the level in different ways

**Comment by mg901** [comment]
@pcottle Ok. Thank you!)
