### ISSUE TITLE
[Bug] Cannot pass level mixed5 in some situation

### ISSUE THREAD

**Issue by dong628** [pcottle/learnGitBranching#1048]
The dev output:

```
{"branches":{"main":{"target":"C1","id":"main","remoteTrackingBranchID":null}},"commits":{"C0":{"parents":[],"id":"C0","rootCommit":true},"C1":{"parents":["C0"],"id":"C1"}},"tags":{},"HEAD":{"target":"main","id":"HEAD"}}
```

![Screenshot_20230110_105818](https://user-images.githubusercontent.com/38680774/211452412-50217b2e-03a7-4b70-817f-8151917ff5b4.jpg)
![Screenshot_20230110_110014](https://user-images.githubusercontent.com/38680774/211452403-591e532c-be15-41b0-82bf-e4d8c79bd4b2.jpg)

After I created 2 commits on "side" branch and created a new branch, the level might no longer be passed.

**Comment by dong628** [comment]
By the way, you are doing a very GREAT job. As they said "It is one of the best resources I found on git". Thank you for your awesome work and thank all the contributors for inproving the i18n and fix bugs, it truly shows the power of community!

**Comment by pcottle** [comment]
Thanks for the kind words! Yes this is because the C7 commit has not been placed below/downstream of the C6 commit.

It has to be C7 -> C6 to pass. Its c10 in this screenshot:
<img width="112" alt="Screen Shot 2023-01-11 at 8 49 08 AM" src="https://user-images.githubusercontent.com/1135007/211851914-8672fe1e-42c2-4898-8ac4-36185a160b6f.png">
vs
<img width="242" alt="Screen Shot 2023-01-11 at 8 49 25 AM" src="https://user-images.githubusercontent.com/1135007/211851979-173825b3-2f1b-4438-89d1-aab1a5869b54.png">

Would you prefer we just look for one more commit on bugFix instead of explicitly C7?

**Comment by dong628** [comment]
Yes, because both Chinese and English discriptions' meaning is that a commit on bugFix represents you are finished, rather than a commit named "C7". Thx!
