### ISSUE TITLE
some clarifications on the diagrams in "git pull" lesson

### ISSUE THREAD

**Issue by Hifilo** [pcottle/learnGitBranching#1080]
Hello, just needed some clarification on the remote diagrams.

The dashed diagram represents the remote repo that I cloned and the solid diagram is my version of that cloned repo that I am working on.

**Comment by Hifilo** [comment]
![chrome_QILmT1ccj8](https://github.com/pcottle/learnGitBranching/assets/92943726/bb7cc045-837b-45fc-8276-3b50d1fe7e3e)

And just a follow up question for my own understanding, when I run `git pull` shouldn't `o/main` end on C4 with main?

**Comment by pcottle** [comment]
Yep, the dashed diagram on the right represents the state of the git repository on the origin server. Think about it like the state that lives inside the GitHub servers.

Git pull would not produce that result, since pulling is taking data from GitHub to your local machine. Push is the way to get the commit #4 onto the server. I'll let the level do more explaining :)

**Comment by Hifilo** [comment]
awesome thank you
