### ISSUE TITLE
Add more clarification on "git branch -f" command

### ISSUE THREAD

**Issue by VladPetriv** [pcottle/learnGitBranching#1115]
The `git branch -f { branch_name } HEAD^` is only allowed if you are not at `{ branch_name }`.
If you are at the `{ branch_name }` you'll receive an error `fatal: cannot force update the branch 'main' checked out at`.
It's not so obvious, so could you please add this clarification on `Branch forcing` page?)

<img width="1011" alt="Знімок екрана 2023-11-14 о 21 49 46" src="https://github.com/pcottle/learnGitBranching/assets/80276277/4a499137-9080-4a46-84a7-509cff2e402c">

**Comment by pcottle** [comment]
Ah yeah so in normal git you aren't allowed to force update the branch you are on.

I felt like it wasnt worthwhile to include this restriction in the lessons, because its just extra work to go to another branch and then go back. It definitely diverges from git normally, but we do that in a few places in the lesson

**Comment by VladPetriv** [comment]
I agree that we should not add this limitation to the practical lessons. Instead, I suggest adding the mention of this limitation to the first page of the theoretical lesson in a format like this:

```text
Note: In a real git environment git branch -f command is not allowed for your current branch.
```

**Comment by pcottle** [comment]
<img width="974" alt="Screenshot 2023-11-21 at 11 36 05 AM" src="https://github.com/pcottle/learnGitBranching/assets/1135007/1586480f-0f59-4045-b7b0-f1bd39f1897b">

**Comment by VladPetriv** [comment]
Thank you)
