### ISSUE TITLE
I am a new open source development and I want to create a feature in the Introduction Sequence. Where should I start?

### ISSUE THREAD

**Issue by darkb0ts** [pcottle/learnGitBranching#1118]
i want create new section in Introduction Sequence and add this command [ git clone, git clean, git  log]

**Comment by pcottle** [comment]
Git log exists! as well as git clone:
https://learngitbranching.js.org/?NODEMO&command=gc;%20git%20log;git%20clone

git clean doesnt make much sense to implement since we don't actually track specific files in our demo. but here is where the code lives in case you want to look around:
https://github.com/pcottle/learnGitBranching/blob/main/src/js/git/index.js
