### ISSUE TITLE
Skip button in the levels

### ISSUE THREAD

**Issue by vikram18rock** [pcottle/learnGitBranching#1152]
Providing the users with a skip button gives more flexibility, they can read the levels, if they already did they can skip the tutorial and jump to the exercise

**Comment by pcottle** [comment]
Would you expect this skip button to be on the level menu, a command line option, or a button in the dialog?

Because theres already functionality for this today! just start a level and hit the Escape button on your keyboard to exit out early:
https://learngitbranching.js.org/?NODEMO&command=level%20intro1

**Comment by vikram18rock** [comment]
Hey, Thank you for replying. And I'm sorry for the delay

I didn't realize about the `esc` till today, but here are the options I can think of
- Mentioning in the intro dialog about the `esc`, because some people can't realize until it's told.
- include in the dialog

And I think skip in the level menu is not required.

And if i can say more, the help buttons that's in bottom right corner, didn't get much of my attention. I don't know why, but I thought I should mention it.

**Comment by vikram18rock** [comment]
That would be great. I tried to do that so many times 🤣.

Thank you for being open for suggestions.

**Comment by pcottle** [comment]
Should be done now! 21fbde2c3122e44c9b7fd80bf36dd21085f1f7ff and a3cfd3bb88b4e15a8ef658fad33b7102d305978a

you can click on the red button in the dialog and itll exit out of the level :)
