### ISSUE TITLE
Feature request: Allow aborting of finished-level dialog

### ISSUE THREAD

**Issue by nicolaiskogheim** [pcottle/learnGitBranching#248]
First: I love your app :heart_eyes: 

When playing I often want to experiment and try out different solutions, and therefore it would be nice if the `reset` command would abort the dialog about finishing the level, and let you skip the animations.

I think `reset` is intuitive, but anything that lets me reset the level after finishing it, in a quick manner, without taking my hands of the keyboard would be great.

**Comment by pcottle** [comment]
Hey @nicolaiskogheim, thats actually a great suggestion! That's a workflow I haven't really considered but having the constant level solved animations (which are quite length) and dialog must get tiring.

It'd be easy to simply remember if you have reset after a level solution and then skip the dialog / animation in this case (since we use the same instances across `reset`s). I'll hack this in real quick -- it will clear when you change levels though.

I had the command prompt echo out `Level solved` just so you have some kind of recognition when you reach the final state (otherwise its a bit confusing). let me know what you think!

(also btdubs -- you can use `Esc` to quit dialogs which wouldnt involve taking your hands off the keyboard)

![screen shot 2015-03-16 at 12 05 15 pm](https://cloud.githubusercontent.com/assets/1135007/6681700/32266576-cc0f-11e4-9ee0-71d16b1dae6b.png)

**Comment by pcottle** [comment]
(also sorry for the delay -- was on PTO for a while and only got back to the grind now)
