### ISSUE TITLE
learnGitBranching - display problem

### ISSUE THREAD

**Issue by zeton3** [pcottle/learnGitBranching#250]
Hi I noticed that something is broken on page http://pcottle.github.io/learnGitBranching/ . All graphical windows are not showing correct. Please fix your page as it is great source of knowledge

**Comment by marcalj** [comment]
I'm waiting too :)

**Comment by likeant** [comment]
Still waiting ...

**Comment by mgarciaisaia** [comment]
Hey, guys - believe it or not, there's a human out there maintaining this
site.

Filling his inbox with 'come on, man - you're taking more than an hour to
fix this' won't help at all - a single bug report is enough.

I'm pretty sure Pete will fix it whenever he has a bit of time for this -
pretty soon, I bet.

In the mean time, anyone can fork the project and publish his/her own fixed
version to be used until he fixes this.

It's great you report problems, but please have the patience the man
deserves :)

Finally, this duplicates #249 :)

**Comment by mayu-yasu** [comment]
Because do not know well how to use the github, it seems had posted without notice . I want to cancel I do not know but how . .><

**Comment by zeton3** [comment]
Hi, 

I did not mean, with creating this issue, to hurry up anyone :-)
I just report to authors that their great work has some problem.
I even don't know if anybody still takes care on this service.....

So guys.
You do a great job with this GIT training! It best that I ever seen.!
I hope that you find time to fix it. It would be great to teach git again  with your service.

And thank you for what you have done. Ale already learn a lot form this.


Cheers!

**Comment by pcottle** [comment]
Hey guys,

Thank you @mgarciaisaia for the kind words! Indeed I am a human, and I'm actually in Manila right now for a work trip (hence on a way different timezone and with spotty internet).

I summarized this in #249 but it sounds like we had a bad push to production from my local machine (probably due to the same internet issues). We have a pretty big suite of tests that cover all the JS functionality, but at the end of the day we push to prod with a bash script that basically rebuilds, adds all the files, and pushes the branch (and then switches back to master).

Aka this beast:
```
grunt lint && git checkout master && git push && git checkout gh-pages && git merge master -m 'merge master' && grunt build && git commit -am 'rebuild for prod' && git push origin gh-pages && git branch -f trunk gh-pages && git checkout master && grunt fastBuild'
```

I'm guessing during the `grunt build` step, somehow the hashed CSS file wasn't added to version control (or failed to be generated) and the rest of the script executed correctly, meaning we pushed a broken version to prod and then switched back.

Anyways I fixed this over in #249 and apologize for the interruption! I'm glad you guys find the site useful (eager issue commenters is a good problem to have) and I'll be more careful when pushing to prod in the future.

Also if anyone has suggestions on an easy way to make test that no 404's register on the site let me know. The tricky thing is that github pages doesn't necessarily update instantly, so you would have to wait until the new version shows up...

**Comment by zeton3** [comment]
Well done! Thank you very much for quick fix.

**Comment by mgarciaisaia** [comment]
@pcottle I've just asked GitHub's support team about what could we do in this situation. There isn't a specific hook for when the site gets updated, but one could probably workaround this in a nasty way using the standard webhooks and polling the build status of the Pages site via [the API](https://developer.github.com/v3/repos/pages/).

Once you know the site got updated, it would be just a matter of using something like a recursive `wget` for checking 404's out.

We could create an issue for this - I'm not implementing this for the moment, and I don't know if/when you would be able to do so, but it would be nice to have it documented.

**Comment by pcottle** [comment]
yeah I actually like polling the build status and maybe checking for the `commit:` field since we would have that locally. let me file an issue!

**Comment by mgarciaisaia** [comment]
OK - James has corrected itself. There **is** a specific hook for when the site gets updated: [`page_build`](https://developer.github.com/webhooks/#events). That should be _way_ easier to do.
