### ISSUE TITLE
Question: fakeTeamwork rebase

### ISSUE THREAD

**Issue by nbartels** [pcottle/learnGitBranching#255]
I try to play with this use case:
* I clone a remote repository
* a team member adds some commits to the remote
* I pull the new commits
* I do some local commits
* **a team member makes a rebase and uses ```push --force``` to override the remote history**
* I pull again

My question is: How I can fake the rebase and ```push --force``` of the remote branch (highlighted step) ?

**Comment by pcottle** [comment]
> a team member makes a rebase and uses push --force to override the remote history

yeah see this is the issue -- `push --force` actually overrides remote history (as you said) so there's total ambiguity on what to actually update the remote repository to if someone else runs it. Your teammate could:

- Rewrite the repo to just a single commit
- Push an entire linux kernel of commits in
- Send a million empty commits

Because of this I didn't implement `fakeTeamwork --push`. Its a bad practice to use (a lot), the result of it is ambiguous, and also would be a headache to implement :)

**Comment by pcottle** [comment]
It's worth noting of course that `git push --force` is supported, but that command doesn't have the ambiguity of //what// to  update the remote repository. `fakeTeamwork` is already a bit weird of a concept (and really just exists for educational purposes).
