### ISSUE TITLE
git cherry-pick command was not taught

### ISSUE THREAD

**Issue by YoHarmonica** [pcottle/learnGitBranching#256]
At Level 'Rebase no. 2', the command [cherry-pick] was used in the solution.
This command hasn't been mentioned in the previous level and was suddenly used in this chapter.

I think it is better to include the cherry-pick lesson before proceeding to the 'Rebase no.2' chapter.

The problem was encountered in the japanese language version. I'm not sure does it happen in the other language's version too or not.

**Comment by pcottle** [comment]
Hey @YoHarmonica !

I think this might be a japanese-specific issue. I see that:
![screen shot 2015-03-29 at 10 09 03 pm](https://cloud.githubusercontent.com/assets/1135007/6890447/5634d992-d660-11e4-9fa9-a97ddd9c83bb.png)

Introduces cherry-pick pretty early on. I actually cant even find the level "Rebase no. 2" -- it might be a legacy level that was removed or renamed at some point.

Anyways closing this out since this is solved for the main app. Do you mind giving me a link to the japanese version? Im assuming its hosted elsewhere... maybe we could merge the translations

**Comment by YoHarmonica** [comment]
hi, pcottle.

Sorry for the late reply. the japanese version of the one I used to learn is here:
http://k.swd.cc/learnGitBranching-ja/?NODEMO

As you mentioned, it indeed is an older version.
