### ISSUE TITLE
Completing a level with the wrong commit names (after using reset) makes the level unfinishable

### ISSUE THREAD

**Issue by OffbeatDrizzle** [pcottle/learnGitBranching#276]
I'm on intro3, and if you make a mistake and use the reset command to undo your changes and then complete the steps properly then the level fails to finish. I am unsure if there is a problem with the reset command I am using, but the tree looks the same as the solution when I have finished.

This fails (start on master branch):
$ git branch bugFix
$ git commit
$ git reset C1
$ git checkout bugFix
$ git commit
$ git checkout master
$ git commit
$ git merge bugFix

This works (start on master branch):
$ git branch bugFix
$ git checkout bugFix
$ git commit
$ git checkout master
$ git commit
$ git merge bugFix

**Comment by pcottle** [comment]
Yep this is intentional -- we compare the actual "hashes" of the commits (aka the C1 vs C2 vs C3) for the solution. this matches how git actually works internally -- when you make that commit and then reset back to bugFix, that commit actually still exists and everything -- its just faded out slightly since no branches point to it.

see the differences in commit hashes below:
![screen shot 2015-05-27 at 9 51 04 pm](https://cloud.githubusercontent.com/assets/1135007/7852900/7ed5ff7e-04ba-11e5-959e-b83663c0984c.png)


![screen shot 2015-05-27 at 9 49 01 pm](https://cloud.githubusercontent.com/assets/1135007/7852884/3e831cc2-04ba-11e5-8356-b1c44ff8da67.png)

everything is incremented by one, so its all off by one. sorry this was confusing but if you had done the command `reset` (by itself) the rest of your solution (The first one) would have worked!
