### ISSUE TITLE
Git merge --no-ff raises an exception

### ISSUE THREAD

**Issue by Lothiraldan** [pcottle/learnGitBranching#279]
While trying to do a git merge --no-ff, it raises a JS exception:

```
Uncaught ReferenceError: upper is not defined
```

Steps to reproduce:

```
git checkout -b branch
git commit
git checkout master
git merge --no-ff branch
```

Tested on firefox 38 and chrome 43

**Comment by pcottle** [comment]
@Lothiraldan can you still repro this? I get the expected behavior:
![screen shot 2015-05-27 at 9 42 00 pm](https://cloud.githubusercontent.com/assets/1135007/7852828/409a24de-04b9-11e5-8790-9e485bf1ee1a.png)

if i actually use `git merge --no-ff branch` i get some error around unspecified arguments, but its just a silly bug with the arg parsing.

Closing out for now but open back up if you can repro

**Comment by Lothiraldan** [comment]
@pcottle It works when using `git merge branch --no-ff` thx
