### ISSUE TITLE
remote o doesn't work in 'Git' push arguments level?

### ISSUE THREAD

**Issue by SevenHong** [pcottle/learnGitBranching#291]
In this level, remote is actually referred as 'origin', so command "git push origin XXX" works but "git push o XXX" is not working, but I thought you actually wanted it to be referred as 'o'?

**Comment by pcottle** [comment]
Oooooh you mean the fact that we have:

![screen shot 2015-06-09 at 11 10 33 am](https://cloud.githubusercontent.com/assets/1135007/8065713/2a6f6320-0e98-11e5-9dca-8ab67c638d94.png)

as the abbrevation? yeah thats confusing -- the only reason why we limit it is because the full `origin/master` doesnt fit in the UI.

let me clarify this

**Comment by pcottle** [comment]
![screen shot 2015-06-09 at 11 17 05 am](https://cloud.githubusercontent.com/assets/1135007/8065862/1302ff0c-0e99-11e5-9f8a-731c8052a837.png)
