### ISSUE TITLE
When re-viewing a multi-page Objective once an exercise has started, it's impossible to see any other page except the last one

### ISSUE THREAD

**Issue by melikyuksel** [pcottle/learnGitBranching#297]
Once the exercise has been started, one can't see previous pages in an Objective window when the Objective button is clicked. This hides the actual Objective on exercises where the last page is often an 'extra tips' sort of page instead of the actual objectives.

**Comment by pcottle** [comment]
Ah yes, this is a limitation with the `objective` command. but running `help level` should relaunch the dialog right?

I actually think since a lot of the dialogs only make sense when seen in order, its better to either start from the beginning or only just see the last page (which is the objective usually).

Do you have a level in mind that has the extra tips page at the end? Maybe I can combine them -- if anything, that should be strictly enforced (rather than fixing the dialog so it can go backwards)

**Comment by melikyuksel** [comment]
Yes, "Juggling Commits" (#1) is the one that I saw this problem on. Not 100% sure about the other ones, but it's just this one I believe.

**Comment by pcottle** [comment]
Alright! Throwing up a PR for at least that level -- lemme know if you spot any others. ideally there would be a way to enforce this via testing but it would be pretty intractable :O
