### ISSUE TITLE
Bugs in level "Grabbing Just 1 Commit"

### ISSUE THREAD

**Issue by GoloTaiwan** [pcottle/learnGitBranching#301]
By doing following commands:
git checkout master
git cherry-pick C4
the branch "bugFix" is still at C4.
Haven't matched the goal but it claims SOLVED.
![grabbing just 1 commit](https://cloud.githubusercontent.com/assets/2368829/8568306/203d723e-259f-11e5-8952-7076d0dc464a.png)

**Comment by pcottle** [comment]
Yep -- did you read the note on the side? Only the master branch gets checked, so since it has a `C4'` commit that its pointing to, thats the only thing you need to solve the level.

so in this level its technically possible to "shortcut" the lesson, but its up to the person reading the level to be honest and not cheat the system :P

There are a few levels where we only do partial checking since there are multiple ways of solving them
