### ISSUE TITLE
Feature/Product Request: Adapt your visualizer to become a strategy tool

### ISSUE THREAD

**Issue by dasjestyr** [pcottle/learnGitBranching#304]
The world lacks a diagramming tool for source control. Your visualizer would be a perfect solution to that. Especially if I can just punch in git commands to visualize. So for example, if I need to create a branching strategy for my next 4 roadmap releases, I could go through the entire process in your tool and have it chart out what that would look like. It would also be great to be able to save that as an ongoing strategy for team collab purposes.

**Comment by pcottle** [comment]
@dasjestyr  we do support "permalinks" so to speak, so you can link people to a specific instance of a tree (or have it playback a sequence of commands)

would that help?

**Comment by dasjestyr** [comment]
I'll have to give it a try. I'm really looking for a documentation tool for visualizing vcs strategy so if that would it into a workflow then I suppose it would help. Although relying on am external site for documentation feels awkward. Maybe a combo of the permalink and image/file export?

-----Original Message-----

**Comment by pcottle** [comment]
Yeah that could work! Here is an example of linking to a permalink with commands:
http://pcottle.github.io/learnGitBranching/?NODEMO&command=git%20commit;%20go%20-b%20side;%20git%20commit

and then loading a tree:
http://pcottle.github.io/learnGitBranching/?NODEMO&command=importTreeNow%20{%22branches%22:{%22master%22:{%22target%22:%22C1%22,%22id%22:%22master%22,%22remoteTrackingBranchID%22:null},%22side%22:{%22target%22:%22C2%22,%22id%22:%22side%22,%22remoteTrackingBranchID%22:null},%22another%22:{%22target%22:%22C3%22,%22id%22:%22another%22,%22remoteTrackingBranchID%22:null}},%22commits%22:{%22C0%22:{%22parents%22:[],%22id%22:%22C0%22,%22rootCommit%22:true},%22C1%22:{%22parents%22:[%22C0%22],%22id%22:%22C1%22},%22C2%22:{%22parents%22:[%22C1%22],%22id%22:%22C2%22},%22C3%22:{%22parents%22:[%22C2%22],%22id%22:%22C3%22}},%22tags%22:{},%22HEAD%22:{%22target%22:%22another%22,%22id%22:%22HEAD%22}}

With some image exporting you could probably get this to work! I believe Raphael.js has support for that

Closing out since I dont think theres much actionable here :)
