### ISSUE TITLE
Shorten the animation after completing a level

### ISSUE THREAD

**Issue by admsteck** [pcottle/learnGitBranching#306]
The animation of the commits falling down and bouncing around is cool, but also really annoying when progressing through the levels and you have to wait for it to complete before getting to the next level.

It looks like it executes the animation twice before continuing.  They all fall, bounce, and come to a stop, then they jump, bounce, and come to a stop again, then they finally jump back up into their starting position.

**Comment by pcottle** [comment]
I don't necessarily want to slow down the first animation (since I actually get feedback that its a cute part of the demo), but I would be open to limiting it (or skipping alltogether) once you have solved a few levels.

I'm wondering if I could use browser session for this. How many levels will you solve at a time?

**Comment by gergelypolonkai** [comment]
How about stopping it if the user clicks anywhere (or a specific “Next”
button maybe…)?

2015-08-26 23:01 GMT+02:00 Peter Cottle <notifications@github.com>:

**Comment by pcottle** [comment]
Wiring in interaction might be a bit hard since you need to interrupt the in-flight promises as they animate. I'd rather not kick it off all together.

It's also unfortunately dependent on screensize -- the larger your screen, the more distant the commits have to fly before they bounce (and lose energy).

What about the 2nd time the animation plays it only does one round, and the third time not at all?

**Comment by admsteck** [comment]
The first round of animation doesn't take that long and is nice, but the second animation after they have already stopped once gets frustrating if doing more than a couple levels.

Another possibility would be to keep track of how many levels have been completed (and how many times the animation has played) in the last couple minutes and reducing or eliminating based on that.  So if someone is going through slowly, they will always see the full animation, but if you are going quickly (like I was doing just for a refresher) you will get less and won't be slowed down by the animations.

That wouldn't require any session storage.  Just save the time (and maybe level number) in local storage when it is completed, remove any times that are more than a minute or two old, and then determine how much animation to show based on how many times are left.

This could even be extended in the future to show the how long it took to complete the level along with how many commands it took.

**Comment by admsteck** [comment]
Another thought I just had, maybe something like a 'hard mode' where the intro dialogs would be disabled along with success animation.  All you would get is the goal window showing you what you need to do and the dialog at the end that shows how many commands it took and lets you move to the next level.

**Comment by pcottle** [comment]
https://dl.dropboxusercontent.com/u/15917930/finish.mov

Woohoo! What do you guys think of the above?

**Comment by pcottle** [comment]
Basically I increment a counter each time you solve a level, transfer that to a speed multiplier that affects the gravity / drag / elasticity of the physics simulation, and then use that to scale up or down the length of the animation.

It's actually a really nice improvement -- I got annoyed waiting for the animation as well @admsteck when cruising through levels but needed the extra push to get this fix in.

I can even follow up and make it part of local storage too...
