### ISSUE TITLE
Wrong titles of few windows

### ISSUE THREAD

**Issue by alexandear** [pcottle/learnGitBranching#340]
Titles of some windows is "Alert!".

I think it should be:
* title "Description" or the same as the heading:
![image](https://cloud.githubusercontent.com/assets/3228886/11457165/9a855d82-96aa-11e5-92e3-ed43b20878e7.png)
![image](https://cloud.githubusercontent.com/assets/3228886/11457182/f9e16f6e-96aa-11e5-9f43-8ee1f516fa35.png)

* title: "Objective"
![image](https://cloud.githubusercontent.com/assets/3228886/11457184/0142217c-96ab-11e5-973f-4c9831a40a2a.png)

**Comment by pcottle** [comment]
Yeah, this is pretty legacy -- we found that when we moved the *actual* title of the content into the modal title, no one ended up reading it since its so tiny and blends into the UI. so we ended up having each modal declare their own titles when appropriate so they could be big and attention grabbing.

we could make them the same, but then it ends up being redundant.

ill close this out for now since i dont think it'll be worth going through and auditing all the different modals we have, but ill keep it in mind from a UX perspective. id also be down to just remove all of them if you want

**Comment by pcottle** [comment]
![screen shot 2015-11-30 at 10 20 11 am](https://cloud.githubusercontent.com/assets/1135007/11480369/f4c63176-974b-11e5-934d-4eb4fce5d3dc.png)
![screen shot 2015-11-30 at 10 20 01 am](https://cloud.githubusercontent.com/assets/1135007/11480370/f4c87fa8-974b-11e5-932d-0a1c315dfbbd.png)

**Comment by pcottle** [comment]
lets drop them -- its cleaner :)

**Comment by pcottle** [comment]
well, lets drop them by default. we will still leave them for the levels dialog since thats semi helpful there

**Comment by alexandear** [comment]
Yeah, it's nice without any titles. Thanks.
