### ISSUE TITLE
What is --aboveAll option in interactive rebase?

### ISSUE THREAD

**Issue by ugultopu** [pcottle/learnGitBranching#373]
In the introduction to rebasing part, there is `--aboveAll` option. In documentation (`git help rebase`), I did not come across such option. Googling `git aboveAll` does not yield much as well. So is `--aboveAll` option something made up for the tutorial or am I missing something?

Many thanks for this awesome project btw.

**Comment by pcottle** [comment]
Oooooh yes. This is very unfortunate :(

its totally an implementation detail and a hack. the situation is, we are trying to show an interactive rebase *while* in a lesson dialog.

that means one dialog launches another dialog, and the default ordering is to have the lesson dialog above the others. so you wouldnt be able to see the rebase view if we used the default command

so we add a hack to basically "elevate" the rebase dialog above all others.

this is confusing though, so I added a line for it:
<img width="979" alt="screen shot 2016-04-27 at 10 36 23 pm" src="https://cloud.githubusercontent.com/assets/1135007/14855939/9a9a4b2c-0cc8-11e6-9bb0-91643af59981.png">

hope that helps!

**Comment by ugultopu** [comment]
Btw, AFAIU this is an issue only for lesson _dialogs_ right? Because I was able to perform successful rebases in questions without using the `--aboveAll` option. If that's the case, then maybe `--aboveAll` can simply be removed from the display (i.e, from the green box in the screenshot) while _actually_ executing the version with `--aboveAll` command. (If the implementation allows such a "deception" though).

**Comment by pcottle** [comment]
> Btw, AFAIU this is an issue only for lesson dialogs right? 

>  If that's the case, then maybe --aboveAll can simply be removed from the display (i.e, from the green box in the screenshot) while actually executing the version with --aboveAll command. (If the implementation allows such a "deception" though).

So yes, we could add (more or less another hack) to strip out the `--aboveAll` from the button text. I guess that's probably a bit cleaner than another line of text explaining it, but it would again have to be a hack (the button would just never render the string --aboveAll despite that being the command).

lemme know if you think that's a good approach and if so, open another task and I can take a stab at it!

**Comment by gergelypolonkai** [comment]
I could imagine an actual solution, but that would be a huge refactor (and
I'm not sure if it's efficient; it's 1am here).

Commands are objects with parameters, some of which are marked as "internal
only". Wen adding a command to a button, the commands toString() method
would be called, which would render it without the internal parameters, but
the command would be called with it.
On Apr 28, 2016 00:36, "Peter Cottle" <notifications@github.com> wrote:

Btw, AFAIU this is an issue only for lesson dialogs right?

If that's the case, then maybe --aboveAll can simply be removed from the
display (i.e, from the green box in the screenshot) while actually
executing the version with --aboveAll command. (If the implementation
allows such a "deception" though).

So yes, we could add (more or less another hack) to strip out the --aboveAll
from the button text. I guess that's probably a bit cleaner than another
line of text explaining it, but it would again have to be a hack (the
button would just never render the string --aboveAll despite that being the
command).

lemme know if you think that's a good approach and if so, open another task
and I can take a stab at it!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/pcottle/learnGitBranching/issues/373#issuecomment-215251891>

**Comment by pcottle** [comment]
yeah thatd be a bigger refactor :P lemme take a crack at removing the text...

**Comment by pcottle** [comment]
<img width="895" alt="screen shot 2016-04-28 at 8 23 37 am" src="https://cloud.githubusercontent.com/assets/1135007/14872024/acce0f2a-0d1a-11e6-9e1a-b002802c8ac0.png">

better :)
