### ISSUE TITLE
Goal tree and solution are not the same

### ISSUE THREAD

**Issue by ugultopu** [pcottle/learnGitBranching#374]
This is rather a nitpicky issue but it has confused me more than once.

For some questions, the goal shown by `show goal` and the solution shown by `show solution` does not arrive at identical trees.

Screenshots:
![remoteadvanced2](https://cloud.githubusercontent.com/assets/9937444/14878042/9a73f4a2-0d29-11e6-8e09-495bb3381643.PNG)
![remote5](https://cloud.githubusercontent.com/assets/9937444/14878047/a3c9fdc6-0d29-11e6-9cd1-f6d63b1097f4.PNG)
For example, in `remoteAdvanced2`, because of how the goal tree looks like, I have tried start with:
`git checkout side1 ; git pull`
but I have received:
`side1 is not a remote tracking branch! I dont know where to push`
I think there are two issues here:
1) It is not apparent that `side1` is a remote tracking branch. Shouldn't it be named `o/side1` instead?
2) The solution and goal tree do not look the same. I would say that they are _functionally_ the same but then in some previous lessons, we have shown that we can refer to a merge commit's first parent by `commit_hash^`. This command won't makes us go to the same commit in both trees.

**Comment by pcottle** [comment]
>  I would say that they are functionally the same

yeah, so I made all the serialization code work to create functionality identical trees, but not necessarily *visually* identical. 

> we have shown that we can refer to a merge commit's first parent by commit_hash^. This command won't makes us go to the same commit in both trees.

yeah, this is a valid exception. tbh i think the whole idea of using `^` when you have more than one parent is weird, since theres some inherent ambiguity. its a good point though that order of parents is not preserved right now (and would require a lot of work to add, but happy to review a PR!)

the reason why you get the error for `git pull` on side1 is because git is trying to do the default `git pull` behavior which means fetching and merging. but side1 is not remote tracking so its ambiguous. the same command would work from master though.

its really an issue with the defaults of git pull. `git pull origin master:master` is a lot more verbose and shows whats going on.

**Comment by pcottle** [comment]
closing this out since theres nothing super actionable on the code sign unfortunately, besides adding parent ordering serialization support which would be quite the challenge for (imo) not a ton of benefit. its awesome you noticed though :)
