### ISSUE TITLE
Add a time line of progress for easy navigation.

### ISSUE THREAD

**Issue by indrajithi** [pcottle/learnGitBranching#376]
It will be better if we add a time line of the progress in the page. Or at least a menu icon. We can easily navigate in the tutorial like in [try.github.io](https://try.github.io).

**Comment by pcottle** [comment]
yeah, the try.github page is much better designed. but it lacks
functionality, which is part of the reason why they can do the timeline --
each segment only allows a very specific command and its not a real file
browser / git installation.

so they can easily rewind you to any state. right now we have an undo
command that does the same, but it could have infinite history and once you
rewind to state 1, you cannot fast-forward again to state 10.

lastly, i dislike the timeline because it implies there is a linear
progression of the tutorial. I instead think it should be more of a "choose
your own adventure" style where YOU choose which lessons you want, and feel
free to veer off the normal progression

On Tue, Jun 7, 2016 at 12:09 AM, Indrajith Indraprastham <
notifications@github.com> wrote:

> It will be better if we add a time line of the progress in the page. We
> can easily navigate in the tutorial like in try.github.io.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/376>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABFRn2WD3PhubA4WsZavC34PYQjozAg_ks5qJRkXgaJpZM4Ivn6Q>
> .
>



-- 
Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(650) 862 3491

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble

**Comment by indrajithi** [comment]
>_I instead think it should be more of a "choose
your own adventure" style where YOU choose which lessons you want, and feel
free to veer off the normal progression_

The design is good. The only problem which I faced was when I want to redo a specific chapter, I will have to reload the page and go to the starting page and choose the appropriate chapter. Adding a menu option to get all the chapters will make this easy. :)

**Comment by pcottle** [comment]
Interesting idea! Ill keep that in mind if I ever do some bigger overhauls to the project
