### ISSUE TITLE
question on 'level mixed1'

### ISSUE THREAD

**Issue by E-nuri** [pcottle/learnGitBranching#408]
## 'level mixed1'
![target](https://cloud.githubusercontent.com/assets/20082776/22959359/1611f2fe-f379-11e6-80f9-fbec2d7a07c2.PNG)

I used 'chckout', 'cherry-pick' to clear this level.
there is bugFix branch under C3(printf). bugFix branch doesn't move to master branch yet.
Is not problem on this level?
(I saw the 'Note' on goal)

![output](https://cloud.githubusercontent.com/assets/20082776/22959442/be29cda4-f379-11e6-9866-2dd4bf036505.PNG)
![result](https://cloud.githubusercontent.com/assets/20082776/22959443/be30be48-f379-11e6-948d-81e123bd894e.PNG)

**Comment by yousifucv** [comment]
I also solved this level but it looks different than the goal.
I did:
git rebase -i master  (deselect C2 and C3)
git checkout master
git cherry-pick bugFix
Solved. But looks different.

**Comment by pcottle** [comment]
this is definitely a valid solution @E-nuri, since master has the bugfix commit (c4).
<img width="514" alt="screenshot 2017-02-17 at 9 24 32 am" src="https://cloud.githubusercontent.com/assets/1135007/23047394/e8530bd4-f4f2-11e6-9605-8fd11b7f61a6.png">

the level finished animation certainly triggered for me.

@yousifucv yours is different since master gets a twice-amended copy of bugFix, aka C4''
<img width="702" alt="screenshot 2017-02-17 at 9 25 38 am" src="https://cloud.githubusercontent.com/assets/1135007/23047447/24f3ca7e-f4f3-11e6-95e2-26399162370a.png">

the goal is to make sure its only amended once. besides, once you have C4' by itself, you could have just moved the branch by doing `go master; git rebase bugFix`

**Comment by E-nuri** [comment]
thanks reply @pcottle @yousifucv

**Comment by EricShui** [comment]
I have one another method , only need two steep :
git rebase -i c1 (click  c2 , c3 's omit)
git branch -f master

**Comment by z6102075** [comment]
yes  i will


 
---Original---
