### ISSUE TITLE
git revert - C2' vs C1

### ISSUE THREAD

**Issue by ddeibert** [pcottle/learnGitBranching#422]
First of all, this is a great resource!  It has really helped with my understanding of the features within git.

This pertains to '4: Reversing Changes in Git' under 'Ramping Up'.

I've been having trouble with the 'git revert' command.  When 'git revert HEAD' is issued against commit C2, the new commit is labeled C2'.  I would expect the new commit to be labeled C1' as it mirrors the parent commit (C1), rather than the C2 commit.

**Comment by pcottle** [comment]
Well the hash decoration is meant to be thought of as the "opposite" or an "updated" version of the commit.

So commit `C2` brings us from the state of where we are at C1 to this new state (at C2). `C2'` is the opposite of that, aka it does the opposite changes as C2. So they end up cancelling out.

So imagine adding up `C1, C2, C2'` -> the latter two cancel out and you are left with C1. I can see why you might want it named after the state in which you end up in, but it gets more obvious when you have multiple commits you want to revert. take for instance the stack:

- C1
- C2
- C3
- C4
- C3'
- C4'
- C2'

With the above, we end up back at C1. And you can tell that each commit was a revert of some commit up in the stack.

But with your naming convention, what happens if we do:
 - C1
 - C2
 - C3
 - C4
 - revert C3?

We do not end up at C2 since we still have C4. In fact, the state of `C1, C2, C4` has *never* existed in our history before, so we have no way to reference it.

**Comment by pcottle** [comment]
hope that helps explain it!
