### ISSUE TITLE
Better solution for level remoteAdvanced1 (Push Master!)

### ISSUE THREAD

**Issue by mtomassoli** [pcottle/learnGitBranching#432]
I learned a lot from this interactive tutorial. Thank you!

Just wanted to point out that you can use `git pull`:
1. git rebase side1 side2
2. git rebase side2 side3
3. git rebase side3 master
4. git pull --rebase
5. git push

**Comment by pcottle** [comment]
Ah that is true, I guess I teach how `git pull --rebase` is shorthand in the level before:

I guess I just try to avoid the magic commands since I think they obscure understanding. good point though! Ill leave this as something where you can beat the optimal solution with a bit of ingenuity :)

![screenshot 2017-07-19 at 12 30 41 pm](https://user-images.githubusercontent.com/1135007/28385769-20302a34-6c7e-11e7-962f-1aef4fad09f0.png)

**Comment by enforcer20** [comment]
Great approach to this problem
