### ISSUE TITLE
`git branch -d` allows deleting not fully merged branches.

### ISSUE THREAD

**Issue by Ethiraric** [pcottle/learnGitBranching#447]
As of now, it  is possible to delete branches that are not fully merged with `git branch -d` (it should require the `-D` switch).

A sample script which demonstrates it:

```sh
git checkout -b toto
git commit
git checkout master
git branch -d toto # Should not work
```

**Comment by pcottle** [comment]
Yeah I remember this nuance; I decided not to implement the `-D` flag since its clear in the UI that only the branch goes away (not the actual commit) and its quite easy to get it back. I think the CLI of git has to be more cautious here, since otherwise you have lost reference to the commit and have to go to reflog to get it back.

lemme know if you think its absolutely required though!

**Comment by pcottle** [comment]
also from a learning standpoint, you'll be fine when you transition to the CLI since the not-knowing-about-this case ends up being a no-op, rather than being destructive

**Comment by Ethiraric** [comment]
I do know about it, but I teach students about git and intend to show them your tool so they can play with branches and have a commit graph in real-time.

While preparing the workshop, I noticed this and was afraid some students might get confused. They are very new to git and explaining them how to use the reflog to go back to the deleted branch would be too difficult.

I do not think it is required, but nonetheless I think it would be a nice addition.

**Comment by pcottle** [comment]
Alright I'll keep this open for now then; I don't do a ton of active development on this anymore but this should be relatively easy to add

**Comment by pcottle** [comment]
(closing out old issues)
