### ISSUE TITLE
undo error

### ISSUE THREAD

**Issue by imba-tjd** [pcottle/learnGitBranching#459]
In level remoteAdvanced8. Steps to reproduce:
```
git pull origin bar:foo
git pull
undo
git pull origin master:side
```
> Your origin branch is out of sync with the remote branch and fetch cannot be performed

**Comment by pcottle** [comment]
yeah hrmmm this shouldn't happen. `undo` should reset both local and origin trees. thats odd

ill look into this later since its probably a pretty complex bug 😨

**Comment by pcottle** [comment]
Ahhh I see whats going on, yes its very tricky. Basically when we reset the state of the world with `undo`, the order of the parents of a given node is not preserved.

Then when we call `makeBranchIfNeeded`, that calls into `findCommonAncestorForRemote` which incorrectly only looks at the first parent of a given node to traverse upwards to find the common ancestor. since C5 is a merge commit, its a bit ambiguous on what to do, but I presume you want the most upstream commit.

the downside is that this is a bug thats been lurking for a while, and pretty hard to fix. let me try and see if I can though

**Comment by pcottle** [comment]
Woohoo! should be fixed / deploying now
