### ISSUE TITLE
Hashes are case sensitive

### ISSUE THREAD

**Issue by machinaut** [pcottle/learnGitBranching#483]
Not sure if this is intentional, since (as far as I know) git hashes are case-insensitive.

**Comment by pcottle** [comment]
Good point! in mercurial they are case insensitive too.

**Comment by pcottle** [comment]
ill update the site with this new code -- its a bit hacky since it just checks for refs that match a `/^c\d+$/` regex and then looks aside for those, but i threw in some test coverage and it should more or less work! lemme know if you see any issues

i tried to add it to a central place but might have missed things
