### ISSUE TITLE
Potential issue on level mixed1

### ISSUE THREAD

**Issue by danielleberre** [pcottle/learnGitBranching#484]
Hi,

I think that there is a small issue in the objective of level mixed1.

The objective shows that the bugFix branch moved with the commit C4'.

The bugFix branch should stay attached to C4, right?

Thanks for that great way to learn git 👍

**Comment by pcottle** [comment]
Glad you like it!

Not quite; `C4` represents the commit we did to fix the bug, and the other commits were just changes we made while debugging. However *any version* of C4 including C4' represents the bugfix.

If you have one commit locally that fixes a bug and you rebase (and receive a new commit hash), its no big deal if it has a new hash -- its the commit thats important.

so yep, either being on C4 or C4' works :)

**Comment by pcottle** [comment]
Ohhh yes I see. thats because the alternate solution is interactive rebase, where you drop two of the commits:
![screenshot 2018-09-29 at 2 56 43 pm](https://user-images.githubusercontent.com/1135007/46250820-ea4c2f80-c3f7-11e8-8f61-69e98b3f8b2f.png)

and then you do `git rebase bugFix master`, which forwards the branch. its also a two step solution, but since it involves an interactive part, its a lot harder to provide it as an automated solution :P

its an odd edge case, but thanks for the feedback! and glad its helping in the classroom

**Comment by danielleberre** [comment]
ok, I see.

Why not using then a solution similar to the rebase exercise?

```
git rebase -i master --solution-ordering C4
```
