### ISSUE TITLE
Use discard/pick on interactive rebase instead of always pick

### ISSUE THREAD

**Issue by danielleberre** [pcottle/learnGitBranching#486]
This is a small remark regarding the interactive rebase panel.

I find counter intuitive to click on a "pick" button to ignore a commit.

I think it would be more intuitive to have by default the label "discard" on the buttons and to toggle it to "pick" when the commit is discarded.

Thanks again for that great tool to learn/teach git!

**Comment by pcottle** [comment]
![screenshot 2018-09-30 at 9 46 37 pm](https://user-images.githubusercontent.com/1135007/46270077-51520d00-c4fa-11e8-92d6-e6a1e15440af.png)

**Comment by pcottle** [comment]
I remember why -- because these backbone views are a pain in the butt :P

basically I wanted that opacity transition via CSS, which means that I cant rejigger the HTML (in backbone) since that would destroy and remount the view (and cancel the animation)

I did this with some hacky CSS logic instead!

**Comment by danielleberre** [comment]
Omit is indeed much better than discard (4 letters just like pick). Thanks for the update.

**Comment by jedeleh** [comment]
Please consider changing the language of the lesson itself to use something besides 'pick' to discuss dropping a commit. It's rather confusing given that 'pick' means to use the commit in the actual rebase interactive editor.

**Comment by jedeleh** [comment]
whoops, I'll make a new issues for that. apologies.
