### ISSUE TITLE
phrasing pick in rebase interactive lesson copy

### ISSUE THREAD

**Issue by jedeleh** [pcottle/learnGitBranching#526]
In the lesson itself, the word 'pick' is used to talk about 'drop' in a rebase interactive editor. It's rather confusing for people new to interactive rebasing since, 'pick' means to use a commit, and 'drop' to get rid of it. I'm not talking about the language on the button in the mock editor--I'm talking about the language in the lesson itself.

**Comment by pcottle** [comment]
Can you screenshot the specific slide / sentence you're referring to? It might be a mistake or intentional, not sure if I remember

**Comment by pcottle** [comment]
(closing out old issues)

**Comment by waldyrious** [comment]
@pcottle this one should be an easy fix — it's just an instance of a poorly worded sentence. The confusing language can be encountered (at least) in the "Interactive Rebase Intro" level:

![Screen Shot 2021-01-04 at 12 42 57](https://user-images.githubusercontent.com/478237/103536690-e63ad200-4e8a-11eb-91ba-5e3eee952163.png)

Here's the relevant code:

https://github.com/pcottle/learnGitBranching/blob/c0bd4df1c9f54696bad1ad4a24bd098a13c2b719/src/levels/rampup/interactiveRebase.js#L79

**Comment by pcottle** [comment]
Ah yes, easy fix. I'll whip up an improvement here

**Comment by waldyrious** [comment]
> I'll whip up an improvement here

Nice, thanks! Happy to provide feedback or suggestions if needed.

**Comment by pcottle** [comment]
![Screen Shot 2021-01-04 at 8 28 59 AM](https://user-images.githubusercontent.com/1135007/103550999-ed4fe900-4e66-11eb-9a41-bf87cc627ca4.png)
This work?

**Comment by waldyrious** [comment]
Yeah, that's great! I would maybe go with "toggle off the `pick` button" instead of "click the `pick` button to toggle it off", just to be extra safe\* but the current wording is much clearer already :)

<sub>\* Because when one starts reading that segment, the brain will automatically interpret "click the `foo` button" as "do the `foo` action" and then it'll have to backtrack when it reaches the very end of the sentence which mentions the word "off". It's a small hiccup, but one we could easily avoid by lifting the negation particle to appear earlier in the sentence.</sub>

**Comment by pcottle** [comment]
Yep agreed that's a bit cleaner. Feel free to send the PR or I can 😅
