### ISSUE TITLE
Spanish translation is too localized

### ISSUE THREAD

**Issue by JoseTomasTocino** [pcottle/learnGitBranching#528]
The translation for the Spanish locale is too localized. Instead of using international, neutral Spanish it's riddled with argentinean expressions, particularly regarding imperatives (_"Aprendé"_ instead of _"Aprenda"_ or _"Tenés"_ instead of _"Tienes"_).

**Comment by Splaktar** [comment]
This appears to be due to the fact that only an Argentinean translation is available for Spanish (https://learngitbranching.js.org/?locale=es_AR).

There don't appear to be translations for locales like the following
* https://learngitbranching.js.org/?locale=es_US
* https://learngitbranching.js.org/?locale=es_ES
* https://learngitbranching.js.org/?locale=es_PE

The full set of Spanish locales
```
es-AR
es-BO
es-CL
es-CO
es-CR
es-DO
es-EC
es-ES
es-GT
es-HN
es-MX
es-NI
es-PA
es-PE
es-PR
es-PY
es-SV
es-US
es-UY
es-VE
```

I looked through the README and Wiki for some guidance on contributing to the translations, but I wasn't able to find anything. I also briefly looked through the repo, but it wasn't clear to me where the translations were stored.

**Comment by pcottle** [comment]
The translations are stored in a very ugly adhoc pattern around different files. The main one is here:
https://github.com/pcottle/learnGitBranching/blob/master/src/js/intl/strings.js

but each level dialog itself also has an internal mapping.

heres where we handle default browser headers and the locales we display in the selector on the page:
https://github.com/pcottle/learnGitBranching/blob/e92fe2c45e4de174126940b176352b562f1e3a09/src/js/stores/LocaleStore.js#L12
https://github.com/pcottle/learnGitBranching/blob/66aaa2ccea3dc2f3172ca6bdda71b5c88195b0a2/src/js/react_views/IntlHelperBarView.jsx

**Comment by pcottle** [comment]
But yeah, I pretty much just accept translations as is since it's not possible for me to review them. Usually the original authors are totally willing to accept edits if you'd like to put up a PR!

**Comment by Splaktar** [comment]
It's strange that https://github.com/pcottle/learnGitBranching/blob/master/src/js/intl/strings.js has `es_ES` translations, but going to https://learngitbranching.js.org/?locale=es_ES gives me an English site (default as no locale mapping found).

It looks like this is because it's not listed in the mapping?
https://github.com/pcottle/learnGitBranching/blob/e92fe2c45e4de174126940b176352b562f1e3a09/src/js/stores/LocaleStore.js#L12-L18

Is this a bug or is the `es_ES` translation still a work in progress?

**Comment by Splaktar** [comment]
Yeah, it looks like `es_ES` is only partially translated. I opened https://github.com/pcottle/learnGitBranching/pull/584 to help reduce this confusion a bit and expose to more people that the `es_ES` translation could use some more input.
