### ISSUE TITLE
Graph is backwards

### ISSUE THREAD

**Issue by sarink** [pcottle/learnGitBranching#590]
In every gui, even a regular ol vanilla `git log`, the most recent information is at the top. Why is it the opposite in this app?

Other suggestion: No git gui or log has arrows. The arrows are very confusing to beginners (although I do understand that they're technically correct, since commits always point to their parents). I wonder if this is something that should show up in a later level, perhaps after a lesson that explains eg `HEAD^`? or something

**Comment by pcottle** [comment]
Oh you mean how the page flows down rather than up? Mainly because the commands are at the top as well (and reading the lesson content flows from top to bottom) so I figured consistency within the app is better. Otherwise you'd be reading on the top and scanning downwards to the bottom constantly (lot of eye motion)

Also ungit kinddddd of has arrows, which I like for the explicitness:
https://github.com/FredrikNoren/ungit

**Comment by itsho** [comment]
First of all - your site is amazing. thank you.

Regarding the current issue: Is there an option to reverse the arrows? or hide them temporarily?

Thank you!

**Comment by pcottle** [comment]
https://github.com/pcottle/learnGitBranching/issues/147

 Check out the flip command!

**Comment by itsho** [comment]
Yes! thank you!
