### ISSUE TITLE
[Proposal] Use more modern tools

### ISSUE THREAD

**Issue by dorian-marchal** [pcottle/learnGitBranching#601]
Hi @pcottle,

I really like `learnGitBranching`, it looks exactly like what I had mind for a side project of mine. :slightly_smiling_face:

Instead of reinventing the wheel or even forking your project, I'd like to contribute.

Would you accept a pull request to replace some of the tools by more modern ones?

Looking at the codebase I suggest:
- Bumping the dependencies.
- Adding prettier.
- Replacing JSHint with ESLint
- Maybe use a more modern flavor of JavaScript (e.g. `let` instead of `var`).
- Replacing grunt with webpack.
- Adding a "proper" watch mode.

I think this would make this project more attractive for contributors.

This would also be a good way for me to become familiar with the codebase as
I plan to help you close some issues afterward, if you are OK with that.

What do you think about this?

**Comment by pcottle** [comment]
That'd be absolutely awesome @dorian-marchal ! I agree on making it more attractive to new contributors -- its quite clearly old (in terms of JS community years) when it comes to the tools and choices made.

I push production on a separate branch in case but like to keep master healthy, so that's usually my only advice. thankfully we have the jenkins integration though so that should keep us honest.

Look forward to any/all improvements! (Also a huge fan of prettier at work)

**Comment by pcottle** [comment]
(closing out old issues, but thankfully a lot of this did get improved!)
