### ISSUE TITLE
`undo` caused exchange of parents

### ISSUE THREAD

**Issue by marbel82** [pcottle/learnGitBranching#613]
When I used undo, the parents of previous commit exchanged.

Bug path:
```bash
$ git commit
$ git checkout C1
$ git commit
$ git commit
$ git branch aa
$ git checkout C3
$ git commit
$ git branch bb
$ git checkout aa
$ git merge bb
$ git checkout master
$ git commit
$ git merge aa
$ git commit

$ undo
```
![image](https://user-images.githubusercontent.com/31281571/66376677-77817700-e9b0-11e9-9e0f-6828e42a0581.png)

**Comment by marbel82** [comment]
State after merge:
```json
{"branches":{"master":{"target":"C8","id":"master","remoteTrackingBranchID":null},"aa":{"target":"C6","id":"aa","remoteTrackingBranchID":null},"bb":{"target":"C5","id":"bb","remoteTrackingBranchID":null}},"commits":{"C0":{"parents":[],"id":"C0","rootCommit":true},"C1":{"parents":["C0"],"id":"C1"},"C2":{"parents":["C1"],"id":"C2"},"C3":{"parents":["C1"],"id":"C3"},"C4":{"parents":["C3"],"id":"C4"},"C5":{"parents":["C3"],"id":"C5"},"C6":{"parents":["C4","C5"],"id":"C6"},"C7":{"parents":["C2"],"id":"C7"},"C8":{"parents":["C6","C7"],"id":"C8"}},"tags":{},"HEAD":{"target":"master","id":"HEAD"}}
```
It seems that `git merge` sets bad parents
```json
"C8":{"parents":["C6","C7"],"id":"C8"}}
```
but before `undo`, when I execute `git checkout HEAD^` HEAD moves to C7. It's working OK.
After undo `git checkout HEAD^` moves HEAD to C6.

**Comment by pcottle** [comment]
@marbel82 this is actually a side effect of what we guarantee with `git undo`. Undo restores the state of the tree to a previous state, but does not guarantee the *ordering* of commit parents.

As you can see, this is reflected visually as the tree being flipped. This also means that commands aren't guaranteed to be able to be replayed exactly (`git checkout HEAD^` for instance uses parent ordering to know where to go).

Unfortunately at this stage its hard to fix this since the tree serialization is pretty baked in. hope thats ok!
