### ISSUE TITLE
[Documentation] Level Builder

### ISSUE THREAD

**Issue by LostKatana** [pcottle/learnGitBranching#630]
I'm missing some documentation on the level builder.
For example how to get a start like in the level remote3.

By now I can't think of how to have the remote this "far" ahead without having the local at least with the remote branchs

**Comment by pcottle** [comment]
Which level are you referring to? 🤔 `builder` is not a level shortcode name

**Comment by LostKatana** [comment]
Sorry for the late answer and the bit sloppy question.
I tried to build some levels on my own but struggle to do so.

It would be nice to have like a step by step tutorial on how to build levels by myself.
I tried to recreate the level "remote3" and failed.

**Comment by pcottle** [comment]
We have this:

<img width="959" alt="Screen Shot 2020-02-22 at 7 50 18 AM" src="https://user-images.githubusercontent.com/1135007/75078082-fd5d2380-5547-11ea-86e1-877b061c1360.png">

would you want more as a step-by-step? its a little tricky since we can only show content before the level builder, we can't really walk you through step-by-step

**Comment by LostKatana** [comment]
Okay thanks.
