### ISSUE TITLE
Suggested level: "Remote Rejected!"

### ISSUE THREAD

**Issue by sorvis** [pcottle/learnGitBranching#631]
Very neat tool thank you for all your great work! 

Here is a level suggestion on how to deal with a remote that has the master branch locked because a pull request system is in place. I have found that this is a common beginner problem where people can get stuck. I wrote this up really quick after I made this mistake just now myself and realized it would make a good level so no problem if we think I should adjust any of my grammar.

Gist: https://learngitbranching.js.org/?gist_level_id=6a4849cb3aa6c3f892d44d0d535a9d83

![image](https://user-images.githubusercontent.com/1037467/73464804-76080000-434d-11ea-9405-0e490dd4f835.png)

![image](https://user-images.githubusercontent.com/1037467/73464833-7e603b00-434d-11ea-9387-6801364c431d.png)

![image](https://user-images.githubusercontent.com/1037467/73464854-861fdf80-434d-11ea-92d8-29bcdffd6f5d.png)

**Comment by pcottle** [comment]
This is a very well-written level and totally a situation someone new to PR's could get into! I also liked how you moved the master branch up so they are starting *after* their mistake.

I went ahead and incorporated this into the curriculum if that's ok 😇 I changed the name of the level slightly but otherwise it's as-is.

Thanks for the awesome contribution!

**Comment by pcottle** [comment]
Should be available now:
https://learngitbranching.js.org/
