### ISSUE TITLE
It's stuck: no continuation

### ISSUE THREAD

**Issue by OnkelTem** [pcottle/learnGitBranching#642]
I was solving "Относительные ссылки №2" task, and was not quite efficient from the first run.
So I clicked "Cancel".

Here comes the **first issue: the task has not been reset, while it should be, right?**

So I entered a command which came first to my mind  - `$ reset` and it worked: the view was reset.
Then I typed another sequence of commands and got "level solved!" in the console finally.
But nothing happens next and this is the **second issue**.

I tried clicking the "Task" button and then green tick in the popup window - it just returns me to the console.

I tried clicking "Goal" button - got just a pop window with the goal obviously.

I tried issuing `$ help` in the console to get the idea of what am I supposed to do next to get the the game running on - but no way, there's nothing useful.

So I'm stuck.

![](https://i.gyazo.com/5cf793e4bbcd128e6a21b4d9244fe248.png)

**Comment by pcottle** [comment]
<img width="1116" alt="Screen Shot 2020-02-22 at 8 24 13 AM" src="https://user-images.githubusercontent.com/1135007/75079626-ba517f00-554c-11ea-8027-5e2af0737981.png">

yeah its because you already solved the level once and *then* reset. we let you know the level is solved again by the echo output, but we don't pop the dialog again.

this was to facilitate people retrying and practicing levels without having to do the annoying dialog finish animation. its also helpful for teachers as well

`levels` is the command you're looking for. ill add that to the command

**Comment by pcottle** [comment]
<img width="442" alt="Screen Shot 2020-02-22 at 8 27 04 AM" src="https://user-images.githubusercontent.com/1135007/75079740-216f3380-554d-11ea-867c-92f69372a5c6.png">
