### ISSUE TITLE
Level "Git push arguments -- Expanded!" does not run demo on screen 3 when clicking button or next

### ISSUE THREAD

**Issue by Yvand** [pcottle/learnGitBranching#768]
Nothing happens and I can't go to next screen.
I tested in both Firefox and Edge Chromium.
Here is the output of debug_copyTree() :

{"branches":{"master":{"target":"C1","id":"master","remoteTrackingBranchID":null}},"commits":{"C0":{"parents":[],"id":"C0","rootCommit":true},"C1":{"parents":["C0"],"id":"C1"}},"tags":{},"HEAD":{"target":"master","id":"HEAD"}}

And thank you for such a useful app !

**Comment by vllbc** [comment]
I'm in the same situation!

**Comment by vllbc** [comment]
**The last level "Git pull arguments"  also has the same situation**

**Comment by pcottle** [comment]
Hey all! I just fixed up the two issues in #766 which might solve this as well -- let me check

**Comment by pcottle** [comment]
*(Btw all of these bugs are related to #751 which I think is a pretty important chunk of work; ideally I caught this with no errors but it's worth fleshing out the few issues to accomplish that task)*

"Git push arguments -- Expanded" is fixed in 766, but the pull arguments is also broken. should be a similar fix, justasec

**Comment by Yvand** [comment]
That was fast !
