### ISSUE TITLE
Awesome tool! + Can it be used on a real repo?

### ISSUE THREAD

**Issue by mtheos** [pcottle/learnGitBranching#784]
This is a fantastic learning tool! The visualiser is wonderful!
I'm comfortable using Git, but this taught me a few new tricks - and a lot about how Git works internally!

Have you looked at running this on a real repo? Would it be possible/feasible to modify it to do that?

I would love to run this on some real repos to see the visualisation.

**Comment by pcottle** [comment]
Hey @mtheos,

Thanks for the kind words! Sadly we can't support running in a real repository easily since we only support branching/commit operations, not the full spectrum of git's functionality. In other words, it's not *actually* git and just a simulation of it.

However another project comes very close to that and is visually great, called ungit:
https://github.com/FredrikNoren/ungit

There's a ton of functionality:
https://www.goguardian.com/blog/engineering/ungit-the-easiest-way-to-use-git/
https://www.youtube.com/watch?v=hkBVAi3oKvo

Heavily recommend checking it out!
