### ISSUE TITLE
Moving away from "Master"

### ISSUE THREAD

**Issue by ankit-1729** [pcottle/learnGitBranching#801]
First of all, a huge thanks for building this supercool Git visualizer. This helped me a lot in my early days.

Coming back, I went through your efforts to move away from "Master". I found something below that you MIGHT want to modify, the wording "Master" to "Main". Ignore if it is intentional.

<img width="1680" alt="Screenshot 2021-02-21 at 15 08 39" src="https://user-images.githubusercontent.com/39479072/108621154-02a0c700-7457-11eb-9fdd-2af03e5486b9.png">

**Comment by pcottle** [comment]
Great catch! I totally forgot I even had customized commit messages. As you can probably tell, I'm doing the master to main switch at a very veneer layer -- all the branches still have the raw ID of "master" which is why I need to find all the places where we are using the raw ID.

Anyways thanks for the report 👏
