### ISSUE TITLE
AutoComplete feature with tab key

### ISSUE THREAD

**Issue by Kaphleamrit** [pcottle/learnGitBranching#842]

**Comment by pcottle** [comment]
Ah yes this would be nice! Not an easy build but something to keep in mind.

In my defense, I don't think git has branch or command autocomplete by default either.

**Comment by tburette** [comment]
I don't think it's a good feature in the context of _learning_.
I recently learned a bit of CISCO ios (a CLI to administer routers). I used autocompletion from the start when exercising.
I ended up realizing that I completely forgot what some shortcuts stood for. What is the t in `configure t` ? No idea!
I'm also convinced that there is such a thing as learning through the fingers : typing things out helps remembering them.

That's subjective and my opinion. I'm curious what others think.

**Comment by pcottle** [comment]
@Ashark I'm supportive of something like an additional tab to swap over to another suggestion. is that the preferred UX you want?

**Comment by Ashark** [comment]
>  something like an additional tab to swap over to another suggestion

This is how it works in PowerShell in Windows. TBH, I do not like such behavior. Because as for me, this is not intuitive that you can _change_ the whole word after it is already typed.

Solution can be for example, either do not complete / do not autosuggest with grey text if the completion it not yet definite.

Another approach (more preferred) is to print suggestions like in bash, and then have the prompt with where you were before that (see screenshot):

![bash git che completion](https://github.com/user-attachments/assets/c6bf7dc0-7c70-48ff-8b33-bcaa432d38d5)

Also, there is approach like in zsh, but I guess this is very hard to implement, so not even asking that :)

**Comment by pcottle** [comment]
What if the completion suggestions were ranked better? Checkout is way more common than cherrypick. Seems like that's where most of the annoyance came from

**Comment by Ashark** [comment]
Yes, the annoyance is because I really needed commit much more often during lesson passing.

> What if the completion suggestions were ranked better? 

As a hotfix this can be done, but tbh, I prefer the bash approach. As this is how you would work in real life (i.e. you would need to add some more letters to make completion definite).

**Comment by pcottle** [comment]
See I actually get annoyed in bash when it wont let me autocomplete because there are multiple choices. I even name my folders with unique prefixes so I dont mess up my autocomplete! haha

**Comment by Ashark** [comment]
> See I actually get annoyed in bash when it wont let me autocomplete because there are multiple choices

Try to switch to zsh! Believe me, it is awesome!

**Comment by pcottle** [comment]
![Screenshot 2024-11-11 at 6 07 46 PM](https://github.com/user-attachments/assets/d4f9b345-4a91-4d02-980d-7575beac4d99)
