### ISSUE TITLE
q: what is "Hg" mode?

### ISSUE THREAD

**Issue by thetayloredman** [pcottle/learnGitBranching#959]
Is "hg" mode some sort of Mercurial compatibility layer? *Why?*

Also bug I guess: when switching from Git to Hg to Git the layout looks different then the initial load (it says Git in the bottom left)

**Comment by pcottle** [comment]
Meta (the company I work at) had to switch from git to mercurial about six years ago, so we had to retrain thousands of engineers in mercurial who were used to using git.

This mercurial compatibility layer allowed us to demonstrate that all of these various commands are just different forms of graph manipulation, and it helped folks retrain by just thinking of the *graph operation* they wanted to do, and then translating that into a command.

So it kind of served as a "common grammar" for both languages to use. I've since left it around in case anyone else finds it helpful
