### ISSUE TITLE
Goal Checking for Juggling Commits #2

### ISSUE THREAD

**Issue by fish-404** [pcottle/learnGitBranching#970]
In the level Juggling Commits#2 (In A Mixed Bag Section), I find if I don't use `amend`, the level can also passed. 
Like these commands: 
```
git checkout main
git cherry-pick C2 C3
```
I see the description in this level is has something like : 

> Remember, the exact number of apostrophe's (') on the commit are not important, only the relative differences. For example, I will give credit to a tree that matches the goal tree but has one extra apostrophe everywhere.

I think maybe the credit shouldn't allow the result only one more apostrophe compare to the original tree ? 

![image](https://user-images.githubusercontent.com/29678177/170813667-9cf392d0-a1d1-42c3-b5f3-9b1a586407c7.png)

**Comment by pcottle** [comment]
Ah yes this comes up now and then; the issue is that there are totally valid solutions that involve only one more apostrophe, for example this one:
<img width="1048" alt="Screen Shot 2022-05-30 at 7 47 56 AM" src="https://user-images.githubusercontent.com/1135007/171005638-7af98b61-b089-4341-9178-be9e0240e28e.png">

The real issue here is that we don't have a way to track "did you amend the contents of C2, and then is that amended commit part of the main branch"? in the above picture I did successfully accomplish that, but in your solution the contents were not amended.

I never implemented some kind of state-tracker to tell if a commit has been amended, since it's somewhat complex -- you'd have to have C2'' track that it was a copy of the amended version of C2 (instead of just copied over twice).

If I had that ability, then I could properly validate the solution to this level :)

**Comment by fish-404** [comment]
Oh, I never thought about this possibility. 
But it seems if use your solution, the newImage branch will point to the new commit. I see the goal shows the newImage branch is point to the original commit. Could it used to checking credits ? 

![Level Goal](https://user-images.githubusercontent.com/29678177/171026683-7af23d30-5b30-457d-a32b-aacdcded22f8.png)

**Comment by pcottle** [comment]
the position of the `newImage` branch doesn't matter, that's why it has the dashed line in the goal dialog. I moved it around in my screenshot before I remembered that :P

**Comment by fish-404** [comment]
OK, now I think I can understand this level more clearly. Thank you for explanation and this project, it's very useful for understand the git commands. ^_^
