### ISSUE TITLE
contributing guide

### ISSUE THREAD

**Issue by brandonmcclure** [pcottle/learnGitBranching#999]
Thank you for this amazing tool! 

It would help myself and other contributors if there was a [github recognized contribute](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) document as well as issue templates to separate bug fixes from features.

**Comment by pcottle** [comment]
Thanks for stopping by @brandonmcclure and your other PR (that I'll review shortly).

I don't necessarily want to be over-prescriptive about contributing templates -- I feel like the split between bug fixes and features is somewhat easy to parse. If there's an easy template we can copy thats gentle then I'll all for that -- but otherwise I wouldn't want to turn anyone away since they feel like they have to follow some paperwork.

We get some REALLY early beginners on this project so I think erring on the side of caution is helpful

**Comment by brandonmcclure** [comment]
That makes a lot of sense. I agree it is best to keep it simple in order to keep the barrier to entry low. I think the information that is in the readme is good, and I created a branch/pr #1001 moving that info into it's own doc. I think this keeps the spirit of the project, while creating the file that github expects/will direct contributors towards. 

I don't really have a good issue template to share. I personally like the consistency that issue templates give me. Without some guidelines I can have problems articulating the actual issue, and that can lead me to avoid contributing/speaking up about the issue because i over analyze what I am typing out, and spend more time on that, than writing code :-)

**Comment by pcottle** [comment]
Commented on #1001, and took a stab at a simple template in:
https://github.com/pcottle/learnGitBranching/blob/main/CONTRIBUTING.md

feel free to edit that with any additional info! I think keeping the build information in the readme (before you submit a PR) is helpful
